//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExCSS.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExCSS.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v2.0.1
        /// *
        /// * Copyright 2012 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world @twitter by @mdo and @fat.
        /// */
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///nav,
        ///section {
        ///  display: block;
        ///}
        ///audio, canvas, video {
        ///  display: inline-block;
        ///  *display: inline;
        ///  *zoom: 1;
        ///}
        ///audio:not([controls]) {
        ///  display: none;
        ///}
        ///html {
        ///  font-size:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bootstrap {
            get {
                return ResourceManager.GetString("Bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /***** Selector Hacks via Paul Irish ******/
        /// 
        ////* IE6 and below */
        ///* html #uno  { color: red }
        /// 
        ////* IE7 */
        ///*:first-child+html #dos { color: red } 
        /// 
        ////* IE7, FF, Saf, Opera  */
        ///html&gt;body #tres { color: red }
        /// 
        ////* IE8, FF, Saf, Opera (Everything but IE 6,7) */
        ///html&gt;/**/body #cuatro { color: red }
        /// 
        ////* Opera 9.27 and below, safari 2 */
        ///html:first-child #cinco { color: red }
        /// 
        ////* Safari 2-3 */
        ///html[xmlns*=&quot;&quot;] body:last-child #seis { color: red }
        /// 
        ////* safari 3+, chrome 1+, opera9+, ff 3.5+ */ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrowserHacks {
            get {
                return ResourceManager.GetString("BrowserHacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import &quot;mystyle.css&quot;;
        ///@import url(&quot;mystyle.css&quot;);
        ///@import url(&quot;fineprint.css&quot;) print;
        ///@import url(&quot;bluish.css&quot;) projection, tv;
        ///@import url(&apos;narrow.css&apos;) handheld and (max-width: 400px);
        ///@import url(layout1.css) screen &quot;Plain style&quot;;
        ///@import url(style4.css) &quot;Four-columns and dark&quot;;
        ///@import &quot;common1.css&quot;;
        ///@import &quot;yellowfish.css&quot; &quot;Yellow Fish&quot;;
        ///
        ///@namespace toto &quot;http://toto.example.org&quot;;
        ///@namespace &quot;http://example.com/foo&quot;;
        ///
        ////* Don&apos;t uncomment the next 2 connents.  They&apos;re part of the test suit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Css3 {
            get {
                return ResourceManager.GetString("Css3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *{}
        ///E{}
        ///E[foo]{}
        ///E[foo=&quot;bar&quot;]{}
        ///E[foo~=&quot;bar&quot;]{}
        ///E[foo^=&quot;bar&quot;]{}
        ///E[foo$=&quot;bar&quot;]{}
        ///E[foo*=&quot;bar&quot;]{}
        ///E[foo|=&quot;en&quot;]{}
        ///E[foo=&quot;bar&quot;][rel=&quot;important&quot;]{}
        ///E:root{} 
        ///E:nth-child(n){}
        ///E:nth-child(odd){}
        ///E:nth-child(even){}
        ///E:nth-last-child(2n+1){}
        ///E:nth-of-type(4n-1){}
        ///E:nth-last-of-type(-n+2){}
        ///E:nth-child(n+2):nth-child(odd):nth-child(-n+9){}
        ///E:first-child{}
        ///E:last-child{}
        ///E:first-of-type{} 
        ///E:last-of-type{}
        ///E:only-child{}
        ///E:only-of-type{}
        ///E:empty{} 
        ///E:link{}
        ///E:visited{}
        ///E:active{}
        ///E:hover{} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Selectors {
            get {
                return ResourceManager.GetString("Selectors", resourceCulture);
            }
        }
    }
}
