name: nuget
description: 'Publish NuGet packages'

inputs:
  dotnet-version:
    description: 'The dotnet framework and SDK version.'
    default: 10.0.x
    required: true
  packages-directory:
    description: 'The root directory of the NuGet packages that should be published'
  server-url:
    description: 'Specifies the NuGet server URL'
    required: true
    default: 'https://api.nuget.org/v3/index.json'

runs:
  using: "composite"
  steps:
    - name: Setup dotnet environment
      uses: actions/setup-dotnet@v3
      id: setup
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Authenticate to NuGet
      shell: bash
      run: |
        # Request OIDC token from GitHub
        OIDC_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
        echo "::add-mask::$OIDC_TOKEN"

        # Use the OIDC token as the API key for NuGet push
        echo "NUGET_API_KEY=$OIDC_TOKEN" >> $GITHUB_ENV

    - name: Publish to NuGet
      working-directory: ${{ inputs.packages-directory }}
      shell: bash
      run: 'dotnet nuget push "*.nupkg" --skip-duplicate --api-key "$NUGET_API_KEY" --source ${{ inputs.server-url }}'